// @vitest-environment jsdom

import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { cleanup, render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { afterEach, describe, expect, it, vi } from "vitest";
import { ReleasesPage } from "./pages";

const apiMocks = vi.hoisted(() => ({
  releases: vi.fn(),
  action: vi.fn(),
  createRelease: vi.fn(),
}));

vi.mock("../../core/api", () => ({
  adminApi: apiMocks,
}));

afterEach(() => {
  cleanup();
  vi.clearAllMocks();
});

describe("ReleasesPage actions", () => {
  it("submits the administrator reason instead of an autogenerated reason", async () => {
    apiMocks.releases.mockResolvedValue({
      items: [
        {
          id: "release-1",
          applicationId: "dex-mobile",
          platform: "android",
          version: "1.2.0",
          buildNumber: 120,
          runtimeVersion: "expo:57.0.15",
          channel: "direct",
          status: "uploaded",
          releaseNotes: [],
          artifact: null,
          rollout: {
            percentage: 10,
            audience: "internal",
            startsAt: null,
            stopRule: null,
          },
          createdAt: "2026-08-25T00:00:00Z",
          updatedAt: "2026-08-25T00:00:00Z",
          activatedAt: null,
          lastAction: null,
        },
      ],
      nextCursor: null,
      hasMore: false,
    });
    apiMocks.action.mockResolvedValue({ release: { id: "release-1" } });
    vi.spyOn(window, "confirm").mockReturnValue(true);

    const queryClient = new QueryClient({
      defaultOptions: { queries: { retry: false } },
    });
    const user = userEvent.setup();
    render(
      <QueryClientProvider client={queryClient}>
        <ReleasesPage />
      </QueryClientProvider>,
    );

    await user.click(await screen.findByRole("button", { name: "校验" }));
    await user.type(
      screen.getByRole("textbox", { name: "操作原因" }),
      "确认安装包元数据完整",
    );
    await user.click(screen.getByRole("button", { name: "确认校验" }));

    expect(apiMocks.action).toHaveBeenCalledWith(
      "release-1",
      "verify",
      "确认安装包元数据完整",
    );
  });
});
